"""Updated baby tracking models

Revision ID: b0d41b78f591
Revises: 
Create Date: 2025-12-14 13:50:13.920770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d41b78f591'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allergy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MILD', 'MODERATE', 'SEVERE', name='severityenum'),
               existing_nullable=False)
        batch_op.alter_column('diagnosed_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'baby_profile', ['baby_id'], ['id'])
        batch_op.drop_column('added_on')

    with op.batch_alter_table('baby_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_in_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'),
               existing_nullable=True)
        batch_op.drop_column('age')
        batch_op.drop_column('added_on')

    with op.batch_alter_table('bath', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'baby_profile', ['baby_id'], ['id'])

    with op.batch_alter_table('checkup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'baby_profile', ['baby_id'], ['id'])

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('last_checkup',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_column('last_update')

    with op.batch_alter_table('diaper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.alter_column('mess_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('WET', 'DIRTY', 'MIXED', name='diapertypeenum'),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'baby_profile', ['baby_id'], ['id'])

    with op.batch_alter_table('feeding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.alter_column('feed_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('BREAST', 'FORMULA', 'SOLID', name='feedtypeenum'),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'baby_profile', ['baby_id'], ['id'])

    with op.batch_alter_table('growth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('head_circumference_cm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recorded_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'baby_profile', ['baby_id'], ['id'])
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('time')
        batch_op.drop_column('head_circumference')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.Enum('GENERAL', 'REMINDER', 'ALERT', name='notificationtypeenum'), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.alter_column('start_time',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'baby_profile', ['baby_id'], ['id'])
        batch_op.drop_column('duration')

    with op.batch_alter_table('track_menu', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('notifications')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notifications_enabled')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('track_menu', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sleep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('notification_type')

    with op.batch_alter_table('growth', schema=None) as batch_op:
        batch_op.add_column(sa.Column('head_circumference', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('height', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('recorded_at')
        batch_op.drop_column('head_circumference_cm')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('feeding', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('feed_type',
               existing_type=sa.Enum('BREAST', 'FORMULA', 'SOLID', name='feedtypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('diaper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('mess_type',
               existing_type=sa.Enum('WET', 'DIRTY', 'MIXED', name='diapertypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DATETIME(), nullable=True))
        batch_op.alter_column('last_checkup',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('checkup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('bath', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('baby_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('age_in_months')

    with op.batch_alter_table('allergy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_on', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('diagnosed_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('severity',
               existing_type=sa.Enum('MILD', 'MODERATE', 'SEVERE', name='severityenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('baby_id')

    # ### end Alembic commands ###
